from config import cfg, DATA_RAW_DIR
from datasets import load_dataset

ds = load_dataset(
    cfg.data.dataset_name,
    split="train",
    streaming=True,
)

samples = []
total_bytes = 0
TARGET_BYTES = cfg.data.max_corpus_mb * 1024 * 1024

for example in ds:
    content = example.get('content', '')
    if not content:
        continue
    if example.get("autogenerated", False):
        continue
    if len(content) > cfg.data.max_file_chars:
        continue

    samples.append(content)
    total_bytes += len(content.encode("utf-8"))
    if total_bytes >= TARGET_BYTES:
        break

print(f'Collected {len(samples)} files, {total_bytes / (1024 * 1024):.2f} MB')

out_path = DATA_RAW_DIR / 'corpus_raw.txt'
with open(out_path, 'w', encoding='utf-8') as f:
    f.write('\n'.join(samples))

print(f'Wrote {out_path} ({out_path.stat().st_size / 1_000_000:.1f} MB)')